keys:
  - &yubikey 5B82BEF3C1A6617707A448FDEB6F11283183E111
  - &JuliansFramework age176a79l7kw5gnecqjw366gps4aft69lvfq0t548lxw39fczf0w3ksz9xxjq
  - &NixOSTesting age1ycjtaq3ez49q20fa2m02ytywqm2gz6qv569ysp69ga2ppy5d0quqew92uz
creation_rules:
  - path_regex: .*/JuliansFramework/.*
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
  - path_regex: .*/NixOSTesting/.*
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *NixOSTesting
  - key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
      - *NixOSTesting
