keys:
  - &yubikey 5B82BEF3C1A6617707A448FDEB6F11283183E111
  - &Jellyfin age1md83lczu3lykmlam62hqg44zu23y655mvat97jfc583kzzjyn4kq48hjn5
  - &Nextcloud-Testing age1cq45a06upwqm6xr3t3hvff7pqvja30xhnrz7va9m8zzvs26ye4js4rm9v2
  - &LocalProxy age1tna8ry2maexe9dld035kk6gy2p6xnfm9lv2ngftamszfqdn2n43s2w3vas
  - &IonosVPS age1mfk3dc4sekgxccv4dyuypavzelv0tvtlerf3s5qwtfzu9rnjevts9qlxme
  - &NixOSTesting age1twvg38sttwpfurkayu0esgyv3t6kvxtu293jr8r5e7catksqwc6sylyvgr
  - &JuliansFramework age176a79l7kw5gnecqjw366gps4aft69lvfq0t548lxw39fczf0w3ksz9xxjq
creation_rules:
  - path_regex: ^secrets/JuliansFramework/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
  - path_regex: ^secrets/NixOSTesting/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *NixOSTesting
  - path_regex: ^secrets/IonosVPS/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *IonosVPS
  - path_regex: ^secrets/LocalProxy/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *LocalProxy
  - path_regex: ^secrets/Nextcloud-Testing/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Nextcloud-Testing
  - path_regex: ^secrets/Jellyfin/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Jellyfin
  - path_regex: ^secrets/[^/]*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
      - *NixOSTesting
      - *IonosVPS
      - *LocalProxy
      - *Nextcloud-Testing
      - *Jellyfin
  - key_groups:
    - pgp:
      - *yubikey
