keys:
  - &yubikey 5B82BEF3C1A6617707A448FDEB6F11283183E111
  - &Valheim age1a0uy4e6rglv5v8hwg8sjrzanl2c54nfccfsw0pa3zle4ur93ldxsx8dmmf
  - &Jellyfin age1md83lczu3lykmlam62hqg44zu23y655mvat97jfc583kzzjyn4kq48hjn5
  - &Nextcloud-Testing age1qdfuc92s2hlzm9sxgf5kp2ln8anx07z0zlka3n5l973x8nwzgfksts33jc
  - &LocalProxy age1tna8ry2maexe9dld035kk6gy2p6xnfm9lv2ngftamszfqdn2n43s2w3vas
  - &IonosVPS age1mfk3dc4sekgxccv4dyuypavzelv0tvtlerf3s5qwtfzu9rnjevts9qlxme
  - &NixOSTesting age1st5jr7qvluvr5tj9n4uftawp29tu8l7vmtjptzu2d0lpyf2v53cqnmmvkk
  - &JuliansFramework age176a79l7kw5gnecqjw366gps4aft69lvfq0t548lxw39fczf0w3ksz9xxjq
creation_rules:
  - path_regex: ^secrets/JuliansFramework/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
  - path_regex: ^secrets/NixOSTesting/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *NixOSTesting
  - path_regex: ^secrets/IonosVPS/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *IonosVPS
  - path_regex: ^secrets/LocalProxy/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *LocalProxy
  - path_regex: ^secrets/Nextcloud-Testing/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Nextcloud-Testing
  - path_regex: ^secrets/Jellyfin/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Jellyfin
  - path_regex: ^secrets/Valheim/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Valheim
  - path_regex: ^secrets/[^/]*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
      - *NixOSTesting
      - *IonosVPS
      - *LocalProxy
      - *Nextcloud-Testing
      - *Jellyfin
      - *Valheim
  - key_groups:
    - pgp:
      - *yubikey
