keys:
  - &yubikey 5B82BEF3C1A6617707A448FDEB6F11283183E111
  - &JuliansFramework age176a79l7kw5gnecqjw366gps4aft69lvfq0t548lxw39fczf0w3ksz9xxjq
  - &NixOSTesting age17lk64gfy88luvumuz0xp2wjwvlgzedatllk5ak9rmqvdmv3g0ewq0q7fcn
creation_rules:
  - path_regex: .*/JuliansFramework/.*
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
  - path_regex: .*/NixOSTesting/.*
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *NixOSTesting
  - key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
      - *NixOSTesting
